version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["vendor/autoload.php"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/dieter1199/Code-Analysis-Tools"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "vue",
    "ember",
    "meteor",
    "angular"
  ]
  environment = [
    "browser",
    "nodejs",
    "mocha",
    "jest",
    "cypress",
    "vitest",
    "mongo",
    "jquery",
    "jasmine"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"